dataset_path: "data/processed/processed.csv"
num_labels: 31
epochs: 10
batch_size: 8
lr: 3e-5
model_name: "facebook/wav2vec2-base-960h"
save_path: "checkpoints/"
val_split: 0.1
early_stop_patience: 3
use_augmentation: true